// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbJL2avV8tXAukcG4eK0mQUBT6BkzivCQ',
    appId: '1:1031003478013:web:48237a78e5f8d0724d6b94',
    messagingSenderId: '1031003478013',
    projectId: 'wujed-379c7',
    authDomain: 'wujed-379c7.firebaseapp.com',
    storageBucket: 'wujed-379c7.firebasestorage.app',
    measurementId: 'G-PVCT9CJGRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Aj9sTeypVPk9MBWf5_lyzHvLWDXNyII',
    appId: '1:1031003478013:android:c50cf70662446b284d6b94',
    messagingSenderId: '1031003478013',
    projectId: 'wujed-379c7',
    storageBucket: 'wujed-379c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6NJ4yH2aHdawF7AArYWeSSqYXJonSX7o',
    appId: '1:1031003478013:ios:aba23343e0c20fc94d6b94',
    messagingSenderId: '1031003478013',
    projectId: 'wujed-379c7',
    storageBucket: 'wujed-379c7.firebasestorage.app',
    iosClientId: '1031003478013-7jfbf3biokposgfktg6q3i9q9jmai7vp.apps.googleusercontent.com',
    iosBundleId: 'com.gp.wujed',
  );
}
